---
- hosts: jenkins_slave
  become: true 
  tasks: 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes 
      cache_valid_time: 3600

  - name: Install AWS CLI
    apt:
      name: awscli
      state: present

  - name: install java 
    apt: 
      name: openjdk-17-jre
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.6-bin.tar.gz
      dest: /opt 
      remote_src: yes
  
  - name: install docker
    apt:
      name: docker.io
      state: present

  - name: start docker services
    service:
      name: docker
      state: started

  - name: give 777 permissions on /var/run/docker.sock
    file:
      path: /var/run/docker.sock
      state: file
      mode: 0777

  - name: start docker on boot time
    service:
      name: docker
      enabled: yes

  - name: Download and install the latest kubectl
    shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      mv kubectl /usr/local/bin/kubectl

  - name: Verify kubectl installation
    command: kubectl version --client --output=yaml
    register: kubectl_version
    ignore_errors: yes

  - name: Print installed kubectl version
    debug:
      msg: "Installed kubectl version: {{ kubectl_version.stdout_lines | default('Kubectl version not found or command failed.') }}"

  - name: Install Helm
    shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  - name: Verify Helm installation
    command: helm version --short
    register: helm_version
    ignore_errors: yes

  - name: Print installed Helm version
    debug:
      msg: "Installed Helm version: {{ helm_version.stdout | default('Helm version not found or command failed.') }}"